### ISSUE TITLE
formatting code with toStringTag Symbol fails

### ISSUE THREAD

**Issue by csizo** [aljazsim/vs-code-typescript-class-organizer#25]
given the following class definition the organize operation fails.

```typescript
export class MyClass {
    get [Symbol.toStringTag]() {
        return 'MyClass';
    }
}
```

The log: 
```
[2020-11-27 12:59:25.892] [exthost] [error] TypeError: Cannot read property 'toString' of undefined
	at new GetterNode (c:\Users\cszol\.vscode\extensions\aljazsim.tsco-1.0.20\out\src\elements\getter-node.js:9:56)
	at Transformer.visitSyntaxTree (c:\Users\cszol\.vscode\extensions\aljazsim.tsco-1.0.20\out\src\transformer.js:69:64)
	at Transformer.visitSyntaxTree (c:\Users\cszol\.vscode\extensions\aljazsim.tsco-1.0.20\out\src\transformer.js:90:22)
	at Transformer.analyzeSyntaxTree (c:\Users\cszol\.vscode\extensions\aljazsim.tsco-1.0.20\out\src\transformer.js:25:18)
	at organizeTypes (c:\Users\cszol\.vscode\extensions\aljazsim.tsco-1.0.20\out\extension.js:241:52)
	at organize (c:\Users\cszol\.vscode\extensions\aljazsim.tsco-1.0.20\out\extension.js:101:22)
	at c:\Users\cszol\.vscode\extensions\aljazsim.tsco-1.0.20\out\extension.js:21:87
	at _executeContributedCommand (c:\Users\cszol\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:699:753)
	at _.$executeContributedCommand (c:\Users\cszol\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:700:104)
	at g._doInvokeHandler (c:\Users\cszol\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:876:926)
	at g._invokeHandler (c:\Users\cszol\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:876:618)
	at g._receiveRequest (c:\Users\cszol\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:875:252)
	at g._receiveOneMessage (c:\Users\cszol\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:874:6)
	at c:\Users\cszol\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:872:136
	at l.fire (c:\Users\cszol\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:67)
	at v.fire (c:\Users\cszol\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:601)
	at c:\Users\cszol\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1066:179
	at l.fire (c:\Users\cszol\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:67)
	at v.fire (c:\Users\cszol\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:601)
	at t.PersistentProtocol._receiveMessage (c:\Users\cszol\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:261:629)
	at c:\Users\cszol\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:258:708
	at l.fire (c:\Users\cszol\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:67)
	at p.acceptChunk (c:\Users\cszol\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:253:989)
	at c:\Users\cszol\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:253:341
	at Socket.t (c:\Users\cszol\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:263:276)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23) tsco.organize
```

**Comment by aljazsim** [comment]
Fixed

**Comment by aaronlippold** [comment]
This doesn't seem to be fixed, as I just ran into it again.

**Comment by aaronlippold** [comment]
```shell
2024-01-13 18:36:07.420 [error] TypeError: Cannot read properties of undefined (reading 'toString')
    at new PropertySignatureNode (/Users/alippold/.vscode/extensions/aljazsim.tsco-1.0.29/src/elements/property-signature-node.ts:19:80)
    at Transformer.visitSyntaxTree (/Users/alippold/.vscode/extensions/aljazsim.tsco-1.0.29/src/transformer.ts:62:84)
    at Transformer.visitSyntaxTree (/Users/alippold/.vscode/extensions/aljazsim.tsco-1.0.29/src/transformer.ts:153:22)
    at Transformer.analyzeSyntaxTree (/Users/alippold/.vscode/extensions/aljazsim.tsco-1.0.29/src/transformer.ts:34:18)
    at organizeTypes (/Users/alippold/.vscode/extensions/aljazsim.tsco-1.0.29/src/helpers/code-helper.ts:391:38)
    at organize (/Users/alippold/.vscode/extensions/aljazsim.tsco-1.0.29/extension.ts:38:54)
    at /Users/alippold/.vscode/extensions/aljazsim.tsco-1.0.29/extension.ts:10:87
    at d.h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:141:140094)
    at d.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:141:140954)
    at l.S (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:10829)
    at l.Q (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:10595)
    at l.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:9685)
    at l.L (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:8764)
    at f.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:7567)
    at n.y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
    at n.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
    at o.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:103:14039)
    at f.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:171:7903)
    at n.y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
    at n.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
    at o.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:103:14039)
    at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:171:6183)
    at MessagePortMain.emit (node:events:513:28)
    at MessagePortMain.emit (node:domain:489:12)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367) tsco.organize {"value":"aljazsim.tsco","_lower":"aljazsim.tsco"}```
